post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imhhc2huYW1lIiwiaWQiOiI2MDM1ZDAxMTI1MTZkMDdkMTBhNDczZDUiLCJpYXQiOjE2MTQxNDEzMTF9.uB2mProi4ZbB3BQioX57brZvlxi30Rn7qTfKksMSogs

{
    "title": "Canonical string reduction", 
    "author": "Edsger W. Dijkstra", 
    "url": "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html"
}

###
post http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "test_abc", 
    "name": "user name", 
    "password": "123456"
}

###
delete http://localhost:3003/api/blogs/6036074f65384b750c1150e1

###
delete http://localhost:3003/api/blogs/6036d0224ee9b683e4563de9
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imhhc2huYW1lIiwiaWQiOiI2MDM1ZDAxMTI1MTZkMDdkMTBhNDczZDUiLCJpYXQiOjE2MTQxNDEzMTF9.uB2mProi4ZbB3BQioX57brZvlxi30Rn7qTfKksMSogs


###
delete http://localhost:3003/api/blogs/6036d0224ee9b683e4563de9
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFiY2RlZiIsImlkIjoiNjAzNWJhZDBmODMxNmIzOGUwZWVmNDdlIiwiaWF0IjoxNjE0MjA0Mzc5fQ.vw7639Csa8acU5EXuhxq-c5LjBj9nwShslHB4R0CBsg

###
delete http://localhost:3003/api/blogs/60370bef7b62a85c9c50af4f
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imhhc2huYW1lIiwiaWQiOiI2MDM1ZDAxMTI1MTZkMDdkMTBhNDczZDUiLCJpYXQiOjE2MTQyMTk3NTR9.rTO614ofA9Fg9xRzhoff4nVos5ZomM0X-OEYes74d60